name: DEPLOY Fake
on:
    workflow_call:
jobs:
    deploy-kubernetes:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de desenvolvimento ${{ secrets.AMBIENTE_ENTREGA }}"
            - name: Deploy fazendo request
              run: "curl -X POST https://webhook.site/1ae8dc95-701b-40b1-b3ab-a9ea26710a58 -d '{ ambiente: ${{secrets.AMBIENTE_ENTREGA}} }'"
