name: Teste Action
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  teste-action-job:
    runs-on: ubuntu-latest
    name: Execucao de action
    steps:
      - name: Adicionando comentário
        uses: WilliamYizima/action-js@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issue-id: ${{ github.event.issue.number }}
          comment: "comentário teste qualquer!!<<<<<"