name: CI-Teste
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Adicionando mensagens de log
              run: |
                echo "::debug:: Mensagem de Log Debug"
                echo "::warning:: Mensagem de Log warning"
                echo "::notice:: Mensagem de Log notice"
                echo "::error:: Mensagem de Log error > erro executado por: ${{github.actor}}"
