name: CI-Teste
on:
    push:
      branches: ["main"]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Adicionando mensagens de log
              run: |
                echos "::debug:: Mensagem de Log Debug"
                echo "::warning:: Mensagem de Log warning"
                echo "::notice:: Mensagem de Log notice"
                echo "::error:: Mensagem de Log error > erro executado por: ${{github.actor}}"
            - name: Logs Agrupados
              run: |
                echo "::group:: Grupo de Logs"
                echo "Info 1"
                echo "Info 2"
                echo "Info 3"
                echo "Info 4"
                echo "Info quem fez: ${{ github.actor }}"
                echo "::endgroup::"